source 'https://rubygems.org'
gem 'aruba'
gem 'gherkin', '=3.2.0'
gem 'gherkin_lint'
gem 'gherkin_format'
gem 'rake'
gem 'rubocop', '~> 0.41.0'
gem 'simplecov', require: false, group: :test
gem 'syllables'
gem 'term-ansicolor'
