source 'https://rubygems.org'
gem 'aruba'
gem 'gherkin', '=2.12.2'
gem 'gherkin_lint'
gem 'gherkin_format'
gem 'rake'
gem 'rubocop'
gem 'simplecov', require: false, group: :test
gem 'syllables'
gem 'term-ansicolor'
